cats/urls.py
from django.urls import path
from . import views


# https://docs.djangoproject.com/en/4.2/topics/http/urls/
app_name = 'cats'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),

]

# Note that make_ = breed_ and auto_= cat_ give us uniqueness within this application

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),  # Add
    path("polls/", include("polls.urls")),
    path("hello/",include("hello.urls")),
    path("admin/", admin.site.urls),
    path("autos/", include("autos.urls")),#add
    path("cats/",include("cats.urls")),
    path("",TemplateView.as_view(template_name ="home/main.html")),

]

cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator as mv
# Create your models here.

class Breed(models.Model):
    name=models.CharField(
        max_length=200,
        validators=[mv (2,"Breed must be greater than ! character")]
        )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[mv(1,"Your cat loves You ! give it a nickname Dang it!!")]
        )
    weight = models.PositiveIntegerField()
    foods= models.CharField(max_length=300)
    breed=models.ForeignKey('Breed', on_delete = models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

cats/forms.py
from django.forms import ModelForm
from cats.models import Breed


# Create the form class.
class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'

cats/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.edit import CreateView , UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Breed,Cat
from cats.forms import BreedForm

# Create your views here.

class MainView(LoginRequiredMixin , View):
    def get(self,request):
        bc=Breed.objects.count()
        ca=Cat.objects.all()

        ctx={'breed_count':bc , 'cats_list':ca}
        return render(request, 'cats/cat_list.html',ctx)

class BreedView(LoginRequiredMixin, View):
    #why do we put View in here
    def get(self,request):
        br= Breed.objects.all()
        ctx={'breed_list':br}
        return render(request,'cats/breed_list.html',ctx)


class BreedCreate(LoginRequiredMixin, View):
    template ='cats/breed_form.html'
    success_url = reverse_lazy('cats:all')

    def get(self,request):
        form=BreedForm() #what does this thing do
        ctx= {'form':form}
        return render(request , self.template ,ctx)

    def post(self,request):
        form=BreedForm(request.POST)#why an argument in this
        if not form.is_valid():
            ctx={'form': form}
            return render(request,self.template,ctx)#what does that self do also that form thingy when its wrong
            #obivously the form is wrong if i'm here isn't it?

        breed= form.save()
        return redirect(self.success_url)


class BreedUpdate(LoginRequiredMixin, View):
    model=Breed
    success_url = reverse_lazy('cats:all')
    template ='cats/breed_form.html'

    def get(self,request,pk):
        breed=get_object_or_404(self.model,pk=pk)
        form=BreedForm(instance=breed)
        ctx={'form':form}
        return render(request, self. template, ctx)

    def post(self,request,pk):
        breed=get_object_or_404(self.model,pk=pk)
        form=BreedForm(request.POST,instance=breed)
        if not form.is_valid():
            ctx={'form':form}
            return render(request, self. template, ctx)

        form.save()
        return redirect(self.success_url)

class BreedDelete(LoginRequiredMixin,View):
    model=Breed
    success_url= reverse_lazy('cats:all')
    template='cats/breed_confirm_delete.html'

    def get(self,request,pk):
        breed=get_object_or_404(self.model , pk=pk)
        ctx={'breed':breed}
        return render(request,self.template,ctx)

    def post(self,request,pk):
        breed=get_object_or_404(self.model,pk=pk)
        breed.delete()
        return redirect(self.success_url)

class CatCreate(LoginRequiredMixin,CreateView):
    model=Cat
    fields='__all__'
    success_url=reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin,UpdateView):
    model=Cat
    fields='__all__'
    success_url=reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin,DeleteView):
    model=Cat
    fields='__all__'
    success_url=reverse_lazy('cats:all')

cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Breed </h1>
<p>Are you sure you want to delete the breed :{{breed}} ?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html"%}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type='submit' value='Submit'>
    <input type="submit" onclick="window.location='{% url 'cats:all' %}'; return false;" value="Cancel">
</form>
{% endblock %}

cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Make List</h1>
{% if breed_list %}
<ul>
    {% for breed in breed_list %}
    <li>
        {{breed.name}}
        (<a href="{% url 'cats:breed_update' breed.id %}">Update</a>|
        <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no breeds!</p>
{% endif %}
<p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
<p><a href="{% url 'cats:all' %}">Back to cats </a></p>
{% endblock %}

cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <h1>Auto List</h1>
  {% if cats_list %}
  <ul>
    {% for cat in cats_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
          {{ cat.food }} ({{ cat.weight }} Kg)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats added.</p>
  {% endif %}
  <p>
    {% if breed_count > 0 %}
      <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
      Please add a breed before you add an cat.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
    <a href="{% url 'cats:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}